### PR TITLE
Fixes #1052 by overloading endsWith assertion

### LINKED ISSUE #1052: Iterables#assertEndsWith should not fail if sequence is empty
#### Summary
Any sequence always ends with an empty sequence. That is always true.

While this may seem silly, the current behaviour limits the usefulness of property-based tests (I was playing around with `junit-quickcheck` when I noticed the error).

#### Example

```xml
...
        <dependency>
            <groupId>org.assertj</groupId>
            <artifactId>assertj-core</artifactId>
            <version>2.8.0</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>com.pholser</groupId>
            <artifactId>junit-quickcheck-generators</artifactId>
            <version>0.7</version>
            <scope>test</scope>
        </dependency>
...
```

```java
public final class Lists {

    public static final List<String> prepend(String head, String... tail) {
        List<String> result = new ArrayList<>(1 + tail.length);
        result.add(head);
        result.addAll(asList(tail));
        return result;
    }
}
```

```java
@RunWith(JUnitQuickcheck.class)
public class ListsTest {

    @Property
    public void prepends_head_to_list(String head, ArrayList<String> strings) {
        String[] tail = strings.toArray(new String[strings.size()]);

        List<String> result = Lists.prepend(head, tail);

        assertThat(result)
                .hasSize(1 + tail.length)
                .startsWith(head)
                .endsWith(tail);
    }
}
```

That will yield:

```
java.lang.AssertionError: Property prepends_head_to_list falsified via shrinking: actual is not empty
Shrunken args: [, []]
Original failure message: [actual is not empty]
Original args: [, []]
Seeds: [-6556694662598446822, -5206529275569188621]


	at org.assertj.core.internal.CommonValidations.failIfEmptySinceActualIsNotEmpty(CommonValidations.java:92)
	at org.assertj.core.internal.Iterables.commonCheckThatIterableAssertionSucceeds(Iterables.java:598)
	at org.assertj.core.internal.Iterables.assertEndsWith(Iterables.java:579)
	at org.assertj.core.api.AbstractIterableAssert.endsWith(AbstractIterableAssert.java:354)
	at org.assertj.core.api.ListAssert.endsWith(ListAssert.java:112)
	at io.xxx.internal.collection.ListsTest.prepends_head_to_list(ListsTest.java:39)
	at sun.reflect.GeneratedMethodAccessor1.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at com.pholser.junit.quickcheck.runner.PropertyVerifier$2.evaluate(PropertyVerifier.java:104)
	at com.pholser.junit.quickcheck.runner.PropertyVerifier$1.evaluate(PropertyVerifier.java:76)
	at com.pholser.junit.quickcheck.runner.PropertyVerifier.verify(PropertyVerifier.java:68)
	at com.pholser.junit.quickcheck.runner.ShrinkNode.verifyProperty(ShrinkNode.java:98)
	at com.pholser.junit.quickcheck.runner.Shrinker.shrink(Shrinker.java:82)
	at com.pholser.junit.quickcheck.runner.PropertyStatement.shrink(PropertyStatement.java:158)
	at com.pholser.junit.quickcheck.runner.PropertyStatement.lambda$property$38(PropertyStatement.java:132)
	at com.pholser.junit.quickcheck.runner.PropertyVerifier$1.evaluate(PropertyVerifier.java:86)
	at com.pholser.junit.quickcheck.runner.PropertyVerifier.verify(PropertyVerifier.java:68)
	at com.pholser.junit.quickcheck.runner.PropertyStatement.verifyProperty(PropertyStatement.java:108)
	at com.pholser.junit.quickcheck.runner.PropertyStatement.evaluate(PropertyStatement.java:92)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:51)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
Caused by: java.lang.AssertionError: actual is not empty
	at org.assertj.core.internal.CommonValidations.failIfEmptySinceActualIsNotEmpty(CommonValidations.java:92)
	at org.assertj.core.internal.Iterables.commonCheckThatIterableAssertionSucceeds(Iterables.java:598)
	at org.assertj.core.internal.Iterables.assertEndsWith(Iterables.java:579)
	at org.assertj.core.api.AbstractIterableAssert.endsWith(AbstractIterableAssert.java:354)
	at org.assertj.core.api.ListAssert.endsWith(ListAssert.java:112)
	at io.xxx.internal.collection.ListsTest.prepends_head_to_list(ListsTest.java:39)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at com.pholser.junit.quickcheck.runner.PropertyVerifier$2.evaluate(PropertyVerifier.java:104)
	at com.pholser.junit.quickcheck.runner.PropertyVerifier$1.evaluate(PropertyVerifier.java:76)
	... 17 more
```

#### Java 8 specific ?

Nope.

### PR DESCRIPTION
**Pull request by fbiville**
The new `endsWith(T[])` allows empty arrays whereas the former
`endsWith(T...)` has been changed to `endsWith(T, T...)` to
explicitly prevent empty varargs.

#### Check List:
* Fixes #1052
* Unit tests : YES
* Javadoc with a code example (API only) : YES

### CODE REVIEW

File: src/main/java/org/assertj/core/api/AbstractObjectArrayAssert.java [hunk 1]
```diff
@@ -890,22 +890,50 @@ public SELF startsWith(@SuppressWarnings("unchecked") ELEMENT... sequence) {
...
    * // assertion will fail
    * assertThat(abc).endsWith("a");</code></pre>
    *
-   * @param sequence the sequence of objects to look for.
+   * @param first the first element of the end sequence of objects to look for.
+   * @param sequence the rest of the end sequence of objects to look for.
    * @return this assertion object.
    * @throws NullPointerException if the given argument is {@code null}.
-   * @throws IllegalArgumentException if the given argument is an empty array.
+   * @throws IllegalArgumentException if the given arguments form an empty array.
```
Comment (fbiville) [inline src/main/java/org/assertj/core/api/AbstractObjectArrayAssert.java]: which is pretty absurd I guess. The prepend can never yield an empty array.

File: src/main/java/org/assertj/core/api/AtomicReferenceArrayAssert.java [hunk 2]
```diff
@@ -917,15 +918,43 @@ public void isEmpty() {
    * // assertion will fail
    * assertThat(abc).endsWith("a");</code></pre>
    *
-   * @param sequence the sequence of objects to look for.
+   * @param first the first element of the end sequence of objects to look for.
+   * @param sequence the rest of the end sequence of objects to look for.
+   * @return this assertion object.
+   * @throws NullPointerException if the given argument is {@code null}.
+   * @throws IllegalArgumentException if the given arguments form an empty array.
```
Comment (fbiville) [inline src/main/java/org/assertj/core/api/AtomicReferenceArrayAssert.java]: which is pretty absurd I guess. The prepend can never yield an empty array.

File: src/main/java/org/assertj/core/internal/Arrays.java [hunk 3]
```diff
@@ -454,8 +465,14 @@ private AssertionError arrayDoesNotStartWithSequence(AssertionInfo info, Failure
     return failures.failure(info, shouldStartWith(array, sequence, comparisonStrategy));
   }
 
+  void assertEndsWith(AssertionInfo info, Failures failures, Object actual, Object first, Object rest) {
+    Object[] sequence = prepend(first, rest);
+    assertEndsWith(info, failures, actual, sequence);
+    checkEmptiness(actual, sequence);
```
Comment (fbiville) [inline src/main/java/org/assertj/core/internal/Arrays.java]: I'm pretty sure `checkEmptiness` is not really needed anymore

File: src/main/java/org/assertj/core/internal/Iterables.java [hunk 4]
```diff
@@ -584,14 +586,34 @@ private AssertionError actualDoesNotStartWithSequence(AssertionInfo info, Iterab
...
+   * @param rest the optional next elements of the end sequence.
+   * @throws NullPointerException if the given argument is {@code null}.
+   * @throws IllegalArgumentException if the given argument is an empty array.
+   * @throws AssertionError if the given {@code Iterable} is {@code null}.
+   * @throws AssertionError if the given {@code Iterable} does not end with the given sequence of objects.
+   */
+  public void assertEndsWith(AssertionInfo info, Iterable<?> actual, Object first, Object[] rest) {
+    Object[] sequence = prepend(first, rest);
+    assertEndsWith(info, actual, sequence);
+    checkNotEmptyIterables(actual, sequence);
```
Comment (fbiville) [inline src/main/java/org/assertj/core/internal/Iterables.java]: I'm pretty sure `checkNotEmptyIterables` is not needed here anymore

**Comment by joel-costigliola** [comment]
Thanks Florent !

**Comment by PascalSchumacher** [comment]
@joel-costigliola Shouldn't this have been merged into 2.x instead of master?

**Comment by joel-costigliola** [comment]
@PascalSchumacher yes, my bad (facepalm)

**Comment by joel-costigliola** [comment]
in 2.x f3b181ce139d36a152181371b908ae473d0691b6

**Comment by fbiville** [comment]
Well, my bad @joel-costigliola I opened the PR against the wrong branch... sorry!
