### PR TITLE
Do no treat Path as Iterable in MapAssert#containsOnlyKeys(Iterable)

### LINKED ISSUE #1751: Updating from 3.11.1 to 3.14.0 breaks
When I try to upgrade assertj-core from 3.11.1 to the latest version 3.14.0. The following code breaks.
```
import static org.assertj.core.api.Assertions.assertThat;

import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.HashMap;
import java.util.Map;

import org.junit.Test;

public class Testassertj {

    @Test
    public void demo() {
        
        Map<Path, String> test = new HashMap<Path, String>();
        Path path = Paths.get("/tmp/test/file");
        test.put(path, "69bf414bf3c9e4a1f9b08bc1bdfbf758b2deb65225eed120e4ff80a065099bd3cfee2f8b815fa2e64206eb447fbd1690a3d196f344852df68f3d45dc820a2cad");
        assertThat(test)
        .containsOnlyKeys(path)
        .containsValue("69bf414bf3c9e4a1f9b08bc1bdfbf758b2deb65225eed120e4ff80a065099bd3cfee2f8b815fa2e64206eb447fbd1690a3d196f344852df68f3d45dc820a2cad");
    }
}
```

The test should pass, but it failed with error:
```
Testassertj
demo(Testassertj)
java.lang.AssertionError: 
Expecting:
  <{/tmp/test/file="69bf414bf3c9e4a1f9b08bc1bdfbf758b2deb65225eed120e4ff80a065099bd3cfee2f8b815fa2e64206eb447fbd1690a3d196f344852df68f3d45dc820a2cad"}>
to contain only following keys:
  <[tmp, test, file]>
keys not found:
  <[tmp, test, file]>
and keys not expected:
  <[/tmp/test/file]>

	at Testassertj.demo(Testassertj.java:22)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:89)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:41)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:541)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:763)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:463)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:209)
```

### PR DESCRIPTION
**Pull request by scordio**
#### Check List:
* Fixes #1751
* Unit tests : YES
* Javadoc with a code example (on API only) : NA

### CODE REVIEW

File: src/test/java/org/assertj/core/api/map/MapAssert_containsOnlyKeys_with_Path_Test.java [hunk 1]
```diff
@@ -0,0 +1,44 @@
...
+  private final Path path = Paths.get("file");
+
+  @Override
+  protected MapAssert<Object, Object> invoke_api_method() {
+    return assertions.containsOnlyKeys(path);
+  }
+
+  @Override
+  protected void verify_internal_effects() {
+    verify(maps).assertContainsOnlyKeys(getInfo(assertions), getActual(assertions), (Object) this.path);
```
Comment (joel-costigliola) [inline src/test/java/org/assertj/core/api/map/MapAssert_containsOnlyKeys_with_Path_Test.java]: Minor: remove this or add it in L36
Add a comment explaining why we need to cast to `Object` as it is not super obvious (to me at least)

**Comment by joel-costigliola** [comment]
nice , just one comment!

**Comment by joel-costigliola** [comment]
Thanks a lot @scordio!
