### PR TITLE
Make configurable if AbstractAssert#equals throws an exception

### LINKED ISSUE #1128: Must AbstractAssert#equals  throw UnsupportedOperationException
#### Summary
@joel-costigliola Is it necessary for the `AbstractAssert#equals` to throw the `UnsupportedOperationException`?
This is against the contract of `Object#equals` and brakes other libraries which are not handling this. I know that it should be the deal of the libraries, if they can handle this error but this situation is absolutely not obvious. Is is possible, to change this?

In fact, currently it breaks the coroutines of Kotlin.

#### Example

```java
org.assertj.core.api.AbstractAssert

  /**
   * {@inheritDoc}
   *
   * @deprecated use {@link #isEqualTo} instead
   *
   * @throws UnsupportedOperationException if this method is called.
   */
  @Override
  @Deprecated
  public boolean equals(Object obj) {
    throw new UnsupportedOperationException("'equals' is not supported...maybe you intended to call 'isEqualTo'");
  }

```

#### Java 8 specific ?

* YES : create Pull Request from the `master` branch
* NO  : create Pull Request from the `2.x` branch

### PR DESCRIPTION
**Pull request by guenhter**
#### Check List:
* Fixes #1128 
* Unit tests : YES
* Javadoc with a code example (API only) : NO

### CODE REVIEW

File: src/main/java/org/assertj/core/api/AbstractAssert.java [hunk 1]
```diff
@@ -50,6 +50,8 @@
  */
 public abstract class AbstractAssert<SELF extends AbstractAssert<SELF, ACTUAL>, ACTUAL> implements Assert<SELF, ACTUAL> {
 
+  public static boolean throwUnsupportedExceptionOnEquals = true;
```
Comment (joel-costigliola) [inline src/main/java/org/assertj/core/api/AbstractAssert.java]: add a comment with a link to https://github.com/joel-costigliola/assertj-core/issues/1128 to make it clear why this field exists.

**Comment by guenhter** [comment]
Done

**Comment by joel-costigliola** [comment]
Thanks @guenhter.
